# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('birthdate', models.DateField()),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
