# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0004_auto_20160119_0109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lecturer', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'subject',
            },
        ),
        migrations.DeleteModel(
            name='Pair',
        ),
    ]
