# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0006_pair'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pair',
            options={'ordering': ['first_week', 'day']},
        ),
        migrations.AddField(
            model_name='pair',
            name='day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='pair',
            table='pairs',
        ),
    ]
