# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 17:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0008_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='StudyMaterial',
        ),
        migrations.AlterModelTable(
            name='studymaterial',
            table='study materials',
        ),
    ]
