# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0009_auto_20160119_1941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studymaterial',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='studymaterial',
            name='message',
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='name',
            field=models.TextField(blank=True),
        ),
    ]
