# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0010_auto_20160119_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pair',
            name='day',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
