# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 20:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0011_auto_20160120_2211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pair',
            options={'ordering': ['first_week', 'time']},
        ),
        migrations.RenameField(
            model_name='pair',
            old_name='day',
            new_name='time',
        ),
    ]
