# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0012_auto_20160120_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pair',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
