# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0014_pair_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pair',
            name='day',
        ),
        migrations.AddField(
            model_name='pair',
            name='weekday',
            field=models.TextField(choices=[(1, '\u041f\u043e\u043d\u0435\u0434\u0456\u043b\u043e\u043a'), (2, '\u0412\u0456\u0432\u0442\u043e\u0440\u043e\u043a'), (3, '\u0421\u0435\u0440\u0435\u0434\u0430'), (4, '\u0427\u0435\u0442\u0432\u0435\u0440'), (5, "\u041f'\u044f\u0442\u043d\u0438\u0446\u044f"), (6, '\u0421\u0443\u0431\u0431\u043e\u0442\u0430')], null=True),
        ),
    ]
