# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 20:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0015_auto_20160120_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pair',
            name='weekday',
        ),
    ]
