# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0018_auto_20160120_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='practice',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
