# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0019_subject_practice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
            ],
            options={
                'db_table': '\u0412\u0438\u043a\u043b\u0430\u0434\u0430\u0447',
            },
        ),
        migrations.AlterModelTable(
            name='pair',
            table='\u041f\u0430\u0440\u0430',
        ),
        migrations.AlterModelTable(
            name='student',
            table='\u0421\u0442\u0443\u0434\u0435\u043d\u0442',
        ),
        migrations.AlterModelTable(
            name='studymaterial',
            table='\u041d\u0430\u0432\u0447\u0430\u043b\u044c\u043d\u0456 \u043c\u0430\u0442\u0435\u0440\u0456\u0430\u043b\u0438',
        ),
        migrations.AlterModelTable(
            name='subject',
            table='\u041f\u0440\u0435\u0434\u043c\u0435\u0442',
        ),
    ]
