# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0024_auto_20160120_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='pair',
            name='lecturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coursework.Lecturer'),
        ),
    ]
