# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 21:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0026_auto_20160120_2346'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='number',
            table='number',
        ),
    ]
