# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 21:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0027_auto_20160120_2347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pair',
            options={'ordering': ['first_week', 'number']},
        ),
    ]
