# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 22:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0029_auto_20160121_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pair',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coursework.Subject'),
        ),
    ]
